name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          command: npm run test

      - name: Upload artifacts
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v7
        with:
         name: Cypress Test Reports
         path: cypress/reports/html # or path/to/artifact

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Cypress Test Reports : https://github.com/karan4689-ind/Cypress-Demo-Project/actions/runs/${{github.run_id}}'
          SLACK_TITLE: Cypress Test Results
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}   