name: Parallel Test Build
on: push
jobs:
  Regression-Test-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
            command: npm run tests:e2e

  Sanity-Test-run:
     runs-on: ubuntu-24.04
     steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
            command: npm run tests:sanity         
       
